#config_version=5

# sound_player:
#   mode_attract_started:
#     intro:
#       action: play
#       loops: 0
#       events_when_stopped: intro_complete
#   intro_complete:
#     introrepeat:
#       action: play
#       loops: -1
#   mode_attract_will_stop:
#     intro:
#       action: stop
#   mode_attract_will_stop.1:
#     introrepeat:
#       action: stop

show_player:
  # mode_attract_started:
  #   attract_init_lights:
  #     loops: 0
  mode_attract_started:
    attract_display_loop:
      loops: -1
  
  
