#config_version=6

shots:
  shot_plunger_lane_exit:
    switch: s_plunger_lane_exit
  shot_pop_lower:
    switch: s_pop_lower
  shot_pop_upper_right:
    switch: s_pop_upper_right
  shot_pop_upper_left:
    switch: s_pop_upper_left
  shot_hj:
    switch: s_hj
  shot_bj:
    switch: s_bj
  shot_zj:
    switch: s_zj
  shot_chance:
    switch: s_chance
  shot_special:
    switch: s_special
  shot_take_hit:
    switch: s_take_hit
  shot_chug_beer:
    switch: s_chug_beer
  shot_do_shot:
    switch: s_do_shot
  shot_kicker_rimrules:
    switch: s_kicker_rimrules
  shot_kicker_mode:
    switch: s_kicker_mode
  shot_quarters:
    switch: s_quarters
  shot_tavern:
    switch: s_tavern_spinner
  shot_pongcup1:
    switch: s_pongcup1
  shot_pongcup2:
    switch: s_pongcup2
  shot_diverter:
    switch: s_diverter
  shot_ramp_drinko:
    switch: s_ramp_upf_entry
  shot_drinko_d:
    switch: s_upf_tgt_left
  shot_drinko_r:
    switch: s_upf_tgt_right
  shot_drinko_i:
    switch: s_horseshoe
  shot_drinko_n:
    switch: s_drinko_n
  shot_drinko_k:
    switch: s_drinko_k
  shot_drinko_o:
    switch: s_drinko_o
  shot_slingquarters:
    switch: s_slingshot_quarters
  shot_slingleft:
    switch: s_slingshot_left
  shot_slingright:
    switch: s_slingshot_right
  shot_tgt_ramp_boot:
    switch: s_tgt_ramp_boot
  shot_tgt_rimrules:
    switch: s_target_rimrules
  shot_laneright_inner:
    switch: s_laneright_inner
    profile: spellbeer_profile
    show_tokens:
      led: lane_right_inner
  shot_laneright_outer:
    switch: s_laneright_outer
    profile: spellbeer_profile
    show_tokens:
      led: lane_right_outer
  shot_laneleft_inner:
    switch: s_laneleft_inner
    profile: spellbeer_profile
    show_tokens:
      led: lane_left_inner
  shot_laneleft_outer:
    switch: s_laneleft_outer
    profile: spellbeer_profile
    show_tokens:
      led: lane_left_outer
  shot_leftflipper:
    switch: s_flipper_left
  shot_rightflipper:
    switch: s_flipper_right