#config_version=6

coils:
  # PD16 - 48V
  # Bank A - N/A (J7) (A0-B0-x)

  # Bank B - P1/P2 (J11) (A0-B1-x)
  c_catch_p1:
    number: A0-B1-0
    default_pulse_ms: 20
  c_sling_p1:
    number: A0-B1-1
    default_pulse_ms: 25
  c_trougheject_p1:
    number: A0-B1-4
    default_pulse_ms: 35
  c_catch_p2:
    number: A0-B1-2
    default_pulse_ms: 20
  c_sling_p2:
    number: A0-B1-3
    default_pulse_ms: 25
  c_trougheject_p2:
    number: A0-B1-5
    default_pulse_ms: 35

  # PD-LED is A1

autofire_coils:
  sling_p1:
    coil: c_sling_p1
    switch: s_sling_p1
  sling_p2:
    coil: c_sling_p2
    switch: s_sling_p2

