#config_version=5

switches:
  # SW16
  # Bank A - P1 (J2) (A0-B0-x)
  s_catch_p1:
    number: A0-B0-0
    type: NC
    ignore_window_ms: 750
  s_sling_p1:
    number: A0-B0-1
  s_start_p1:
    number: A0-B0-2
    tags: start
  s_trougheject_p1:
    number: A0-B0-3
    type: NC

  # Bank B - P2 (J6) (A0-B1-x)
  s_catch_p2:
    number: A0-B1-0
    type: NC
    ignore_window_ms: 750
  s_sling_p2:
    number: A0-B1-1
  s_start_p2:
    number: A0-B1-2
    tags: start
  s_trougheject_p2:
    number: A0-B1-3
    type: NC
  
  
  
  
  
  
  
  
